'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';
import { updateUserProfile } from '@/lib/userProfile';
import { LEARN_LANGUAGES } from '@/data/languages';

// ── Constants ─────────────────────────────────────────────────────────────────
const LEVEL_XP: Record<string, number> = {
  a1: 0, a2: 800, b1: 1400, b2: 2400, c1: 4000, c2: 6500,
};
const LEVEL_META: Record<string, { label: string; desc: string; emoji: string; color: string }> = {
  a1: { label: 'A1 · Beginner',           desc: 'Start with the basics',        emoji: '🌱', color: '#059669' },
  a2: { label: 'A2 · Elementary',         desc: 'Everyday conversations',        emoji: '🌿', color: '#0D9488' },
  b1: { label: 'B1 · Intermediate',       desc: 'Handle most daily situations',  emoji: '⚡', color: '#2563EB' },
  b2: { label: 'B2 · Upper-Intermediate', desc: 'Discuss complex topics',        emoji: '🔥', color: '#7C3AED' },
  c1: { label: 'C1 · Advanced',           desc: 'Express yourself fluently',     emoji: '💎', color: '#DB2777' },
  c2: { label: 'C2 · Mastery',            desc: 'Near-native proficiency',       emoji: '👑', color: '#D97706' },
};

const TRACK_META = {
  travel:   { label: 'Travel & Life',      emoji: '🧳', color: '#059669', desc: 'Airports, restaurants, hotels — real-world survival conversations' },
  business: { label: 'Business & Career',  emoji: '💼', color: '#2563EB', desc: 'Emails, meetings, negotiations — professional workplace language' },
  study:    { label: 'Study & Exam',       emoji: '🎓', color: '#7C3AED', desc: 'Grammar, reading, exam prep — systematic structured learning' },
};
type TrackKey = keyof typeof TRACK_META;

// ── Track questions (language-agnostic — about goals & habits) ────────────────
const TRACK_QUESTIONS = [
  {
    q: 'Why are you learning this language?',
    options: ['Travel & tourism', 'Work & business', 'School / exams', 'Hobby & culture'],
    weights: { travel: [3,0,0,1], business: [0,3,0,0], study: [0,0,3,1] },
  },
  {
    q: 'How much time can you study each day?',
    options: ['Under 15 min', '30 minutes', '1 hour', 'More than 1 hour'],
    weights: { travel: [2,1,0,0], business: [0,1,1,2], study: [0,0,2,2] },
  },
  {
    q: 'Which skill matters most to you?',
    options: ['Speaking & conversation', 'Business writing', 'Grammar & reading', 'Listening & pronunciation'],
    weights: { travel: [3,0,0,1], business: [1,3,0,0], study: [0,0,3,1] },
  },
  {
    q: 'Where will you mainly use this language?',
    options: ['While travelling abroad', 'At work / company', 'In class / assignments', 'Everyday hobbies'],
    weights: { travel: [3,0,0,1], business: [0,3,0,0], study: [0,0,3,1] },
  },
  {
    q: 'What is your current level?',
    options: ['Complete beginner', 'Know basic greetings', 'Can hold simple conversations', 'Fairly comfortable'],
    levels: ['a1', 'a1', 'a2', 'b1'],
    weights: { travel: [1,1,1,1], business: [1,1,1,1], study: [1,1,1,1] },
  },
];

// ── CEFR questions generated by Gemini ────────────────────────────────────────
interface Question {
  id: number; level: string;
  q: string; options: string[]; answer: number;
}

type Phase = 'intro' | 'track' | 'loading' | 'cefr' | 'result' | 'error';

function buildGeminiPrompt(langLabel: string, nativeLabel: string): string {
  return `You are a language assessment expert. Generate exactly 10 multiple-choice CEFR placement questions for a student learning ${langLabel}. The student's native language is ${nativeLabel}.

Write all question text and answer options IN ${langLabel}.

Rules:
- 2 questions each for: A1, A2, B1, B2, C1
- 4 options per question (A B C D)
- Vary which index (0,1,2,3) is correct — never always index 0
- Test grammar, vocabulary or comprehension appropriate to each level

Return ONLY valid JSON, no markdown:
{"questions":[{"id":1,"level":"a1","q":"...","options":["...","...","...","..."],"answer":2},...]}`;
}

function ProgressBar({ pct, color = '#6366F1' }: { pct: number; color?: string }) {
  return (
    <div style={{ height: 4, background: '#334155', borderRadius: 99, overflow: 'hidden' }}>
      <div style={{ height: '100%', width: `${pct}%`, background: color, borderRadius: 99, transition: 'width .5s ease' }} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
function PlacementInner() {
  const router       = useRouter();
  const searchParams = useSearchParams();
  const { user, profile, refreshProfile } = useAuth();

  const learnLang  = profile?.learnLang  || (typeof window !== 'undefined' ? localStorage.getItem('mt_learn_lang') : null)  || searchParams.get('lang')  || 'en-US';
  const nativeLang = profile?.nativeLang || (typeof window !== 'undefined' ? localStorage.getItem('mt_native_lang') : null) || 'ko-KR';
  const langInfo   = LEARN_LANGUAGES.find(l => l.code === learnLang);
  const nativeInfo = LEARN_LANGUAGES.find(l => l.code === nativeLang);
  const langLabel   = langInfo?.native   || langInfo?.label   || 'English';
  const nativeLabel = nativeInfo?.native || nativeInfo?.label || 'Korean';

  const [phase, setPhase]           = useState<Phase>('intro');
  const [trackStep, setTrackStep]   = useState(0);
  const [trackAnswers, setTrackAnswers] = useState<number[]>([]);
  const [trackResult, setTrackResult]   = useState<{ track: TrackKey; scores: Record<string,number>; levelHint: string } | null>(null);

  const [questions, setQuestions]   = useState<Question[]>([]);
  const [cefrStep, setCefrStep]     = useState(0);
  const [cefrAnswers, setCefrAnswers] = useState<(number|null)[]>([]);
  const [cefrSelected, setCefrSelected] = useState<number|null>(null);
  const [cefrRevealed, setCefrRevealed] = useState(false);
  const [cefrLevel, setCefrLevel]   = useState('a1');

  const [loadErr, setLoadErr]       = useState('');
  const [saving, setSaving]         = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout>|null>(null);

  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);

  // ── TRACK: answer handler ────────────────────────────────────────────────
  const handleTrackAnswer = (optIdx: number) => {
    const newAnswers = [...trackAnswers, optIdx];
    if (trackStep < TRACK_QUESTIONS.length - 1) {
      setTrackAnswers(newAnswers);
      setTrackStep(s => s + 1);
    } else {
      // compute track scores
      const scores: Record<string,number> = { travel: 0, business: 0, study: 0 };
      let levelHint = 'a1';
      TRACK_QUESTIONS.forEach((q, qi) => {
        (Object.keys(scores) as TrackKey[]).forEach(t => {
          scores[t] += (q.weights[t]?.[newAnswers[qi]] ?? 0);
        });
        if (q.levels) levelHint = q.levels[newAnswers[qi]];
      });
      const track = (Object.keys(scores) as TrackKey[]).reduce((a, b) => scores[a] > scores[b] ? a : b);
      setTrackResult({ track, scores, levelHint });
      setTrackAnswers(newAnswers);
      setPhase('loading');
      generateCefrQuestions();
    }
  };

  // ── CEFR: load pregenerated JSON first, fallback to Gemini ─────────────
  const generateCefrQuestions = async () => {
    setLoadErr('');
    try {
      // 1️⃣ 사전 생성 JSON 먼저 시도 (빠름, API 호출 없음)
      let qs: Question[] | null = null;
      try {
        const preRes = await fetch(`/placement-questions/${learnLang}.json`);
        if (preRes.ok) {
          const preData = await preRes.json();
          if (Array.isArray(preData.questions) && preData.questions.length >= 8) {
            // 매번 같은 문제 방지 — 랜덤 셔플
            const shuffled = [...preData.questions].sort(() => Math.random() - 0.5);
            qs = shuffled.slice(0, 10);
            console.log(`[placement] ✅ Loaded pregenerated questions for ${learnLang}`);
          }
        }
      } catch { /* pregenerated 없으면 Gemini로 fallback */ }

      // 2️⃣ 사전 생성 없으면 Gemini 실시간 생성
      if (!qs) {
        console.log(`[placement] 🤖 Generating with Gemini for ${learnLang}...`);
        const res = await fetch('/api/gemini', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            uid:         user?.uid || null,
            purpose:     'placement',
            prompt:      buildGeminiPrompt(langLabel, nativeLabel),
            temperature: 0.4,
          }),
        });
        const data = await res.json();
        if (!res.ok || !data.text) throw new Error(data.message || 'AI generation failed');
        const clean = data.text.replace(/```json\s*/gi,'').replace(/```\s*/g,'').trim();
        const parsed = JSON.parse(clean);
        qs = parsed.questions;
      }

      if (!Array.isArray(qs) || qs.length < 5) throw new Error('Invalid response format');
      setQuestions(qs);
      setCefrAnswers(Array(qs.length).fill(null));
      setCefrStep(0);
      setCefrSelected(null);
      setCefrRevealed(false);
      setPhase('cefr');
    } catch (e: any) {
      console.error('[placement]', e);
      setLoadErr(e.message || 'Something went wrong');
      setPhase('error');
      setTrackAnswers([]);
    }
  };

  // ── CEFR: answer handler ─────────────────────────────────────────────────
  const handleCefrAnswer = (optIdx: number) => {
    if (cefrRevealed) return;
    setCefrSelected(optIdx);
    setCefrRevealed(true);
    const newAnswers = [...cefrAnswers];
    newAnswers[cefrStep] = optIdx;
    setCefrAnswers(newAnswers);
    timerRef.current = setTimeout(() => {
      if (cefrStep + 1 >= questions.length) {
        computeCefrResult(newAnswers);
      } else {
        setCefrStep(s => s + 1);
        setCefrSelected(null);
        setCefrRevealed(false);
      }
    }, 900);
  };

  const handleCefrSkip = () => {
    const newAnswers = [...cefrAnswers];
    if (cefrStep + 1 >= questions.length) computeCefrResult(newAnswers);
    else { setCefrStep(s => s + 1); setCefrSelected(null); setCefrRevealed(false); }
  };

  const computeCefrResult = (ans: (number|null)[]) => {
    const scores: Record<string,number> = { a1:0, a2:0, b1:0, b2:0, c1:0 };
    questions.forEach((q,i) => {
      const lvl = ['a1','a2','b1','b2','c1'].includes(q.level) ? q.level : 'c1';
      if (ans[i] === q.answer) scores[lvl]++;
    });
    const order = ['a1','a2','b1','b2','c1'];
    let result = trackResult?.levelHint || 'a1';
    // override with actual quiz performance
    let overrideResult = 'a1';
    for (const lvl of order) {
      const total = questions.filter(q => q.level === lvl).length || 2;
      if (scores[lvl] >= Math.ceil(total * 0.5)) overrideResult = lvl;
      else break;
    }
    const c1Total = questions.filter(q => q.level === 'c1').length;
    if (c1Total > 0 && scores['c1'] === c1Total) overrideResult = 'c2';
    // blend: if levelHint is higher than quiz result, stay with quiz (be conservative)
    const order2 = ['a1','a2','b1','b2','c1','c2'];
    const hintIdx = order2.indexOf(trackResult?.levelHint || 'a1');
    const quizIdx = order2.indexOf(overrideResult);
    result = order2[Math.min(hintIdx, quizIdx + 1)]; // allow 1 level above quiz at most
    setCefrLevel(result);
    setPhase('result');
  };

  // ── SAVE & GO ────────────────────────────────────────────────────────────
  const handleApply = async () => {
    if (!trackResult) return;
    setSaving(true);
    const xp = LEVEL_XP[cefrLevel] || 0;
    try {
      if (user) {
        await updateUserProfile(user.uid, {
          xp,
          placementLevel: cefrLevel,
          placementTrack: trackResult.track,
          placementDone:  true,
        } as any);
        await refreshProfile();
      }
      localStorage.setItem('mt_xp', String(xp));
      localStorage.setItem('mt_placement_done',  'true');
      localStorage.setItem('mt_placement_level', cefrLevel);
      localStorage.setItem('mt_track',           trackResult.track);
    } catch (e) { console.error(e); }
    setSaving(false);
    router.push('/lingua');
  };

  const resetAll = () => {
    setPhase('intro');
    setTrackStep(0); setTrackAnswers([]); setTrackResult(null);
    setQuestions([]); setCefrStep(0); setCefrAnswers([]);
    setCefrSelected(null); setCefrRevealed(false);
    setLoadErr('');
  };

  // ── Derived ───────────────────────────────────────────────────────────────
  const cefrQ       = questions[cefrStep];
  const cefrQLevel  = cefrQ ? (LEVEL_META[cefrQ.level] || LEVEL_META['c1']) : null;
  const levelInfo   = LEVEL_META[cefrLevel];
  const trackInfo   = trackResult ? TRACK_META[trackResult.track] : null;
  const totalTrackScore = trackResult ? Object.values(trackResult.scores).reduce((a,b)=>a+b,0) : 1;
  const cefrCorrect = cefrAnswers.filter((a,i) => questions[i] && a === questions[i].answer).length;

  // ════════════════════════════════════════════════════════════════════════════
  // ERROR
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'error') return (
    <div style={{ minHeight:'100vh', background:'#0F172A', display:'flex', alignItems:'center', justifyContent:'center', fontFamily:"'Nunito',sans-serif", padding:20 }}>
      <div style={{ textAlign:'center', maxWidth:400 }}>
        <div style={{ fontSize:56, marginBottom:16 }}>⚠️</div>
        <div style={{ fontSize:22, fontWeight:900, color:'#F1F5F9', marginBottom:8 }}>
          Question generation failed
        </div>
        <div style={{ fontSize:14, color:'#94A3B8', marginBottom:24, lineHeight:1.6 }}>
          {loadErr || 'Could not load level test questions.'}<br/>
          This is usually a temporary API issue.
        </div>
        <button
          onClick={() => { setPhase('loading'); generateCefrQuestions(); }}
          style={{ background:'#6366F1', color:'#fff', border:'none', borderRadius:12, padding:'12px 28px', fontWeight:800, fontSize:15, cursor:'pointer', marginRight:12 }}
        >
          🔄 Try Again
        </button>
        <button
          onClick={async () => {
            localStorage.setItem('mt_placement_done', 'true');
            localStorage.setItem('mt_placement_level', 'a1');
            if (user) {
              await updateUserProfile(user.uid, {
                placementDone: true, placementLevel: 'a1', placementTrack: 'travel',
              }).catch(() => {});
            }
            router.push('/lingua');
          }}
          style={{ background:'#1E293B', color:'#94A3B8', border:'1px solid #334155', borderRadius:12, padding:'12px 28px', fontWeight:800, fontSize:15, cursor:'pointer' }}
        >
          Skip Test
        </button>
      </div>
    </div>
  );

  // ════════════════════════════════════════════════════════════════════════════
  // INTRO
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'intro') return (
    <div style={{ minHeight:'100vh', background:'#0F172A', display:'flex', alignItems:'center', justifyContent:'center', fontFamily:"'Nunito',sans-serif", padding:20 }}>
      <style suppressHydrationWarning dangerouslySetInnerHTML={{ __html:`
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');
        @keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}
        @keyframes pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.03)}}
      `}} />
      <div style={{ maxWidth:500, width:'100%', textAlign:'center', animation:'fadeUp .5s ease' }}>
        {/* Flag + title */}
        <div style={{ fontSize:56, marginBottom:16 }}>{langInfo?.flag || '🌐'}</div>
        <div style={{ fontSize:12, fontWeight:900, color:'#6366F1', letterSpacing:2, textTransform:'uppercase', marginBottom:10 }}>
          Personalised Placement
        </div>
        <h1 style={{ fontSize:30, fontWeight:900, color:'#fff', margin:'0 0 12px', lineHeight:1.2 }}>
          Find your {langLabel} level<br/>& learning track
        </h1>
        <p style={{ fontSize:15, color:'#94A3B8', lineHeight:1.7, margin:'0 0 28px' }}>
          <strong style={{ color:'#CBD5E1' }}>2 steps · ~4 minutes</strong><br/>
          5 questions to find your track, then 10 questions to nail your CEFR level.
        </p>

        {/* Steps preview */}
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:28 }}>
          {[
            { emoji:'🧭', label:'Step 1', desc:'Track match\n5 questions', color:'#F59E0B' },
            { emoji:'🎯', label:'Step 2', desc:`${langLabel} level\n10 questions`, color:'#6366F1' },
          ].map((s,i) => (
            <div key={i} style={{ background:'#1E293B', borderRadius:14, padding:'16px', border:'1px solid #334155' }}>
              <div style={{ fontSize:28, marginBottom:8 }}>{s.emoji}</div>
              <div style={{ fontSize:12, fontWeight:900, color:s.color, letterSpacing:1 }}>{s.label}</div>
              <div style={{ fontSize:11, color:'#64748B', fontWeight:700, marginTop:4, whiteSpace:'pre-line' }}>{s.desc}</div>
            </div>
          ))}
        </div>

        {/* Tracks preview */}
        <div style={{ display:'flex', flexDirection:'column', gap:8, marginBottom:28 }}>
          {(Object.entries(TRACK_META) as [TrackKey, typeof TRACK_META.travel][]).map(([k,v]) => (
            <div key={k} style={{ background:'#1E293B', borderRadius:12, padding:'12px 16px', border:'1px solid #334155', display:'flex', alignItems:'center', gap:12, textAlign:'left' }}>
              <span style={{ fontSize:22 }}>{v.emoji}</span>
              <div>
                <div style={{ fontSize:13, fontWeight:900, color:v.color }}>{v.label}</div>
                <div style={{ fontSize:11, color:'#64748B', fontWeight:700 }}>{v.desc}</div>
              </div>
            </div>
          ))}
        </div>

        {loadErr && (
          <div style={{ background:'#450A0A', border:'1px solid #DC2626', borderRadius:12, padding:'11px 16px', marginBottom:16, color:'#FCA5A5', fontSize:13, fontWeight:700 }}>
            ⚠️ {loadErr}
          </div>
        )}

        <button onClick={() => setPhase('track')}
          style={{ width:'100%', padding:'15px', borderRadius:14, border:'none', background:'linear-gradient(135deg,#6366F1,#8B5CF6)', color:'#fff', fontSize:16, fontWeight:900, cursor:'pointer', fontFamily:"'Nunito',sans-serif", boxShadow:'0 8px 24px rgba(99,102,241,0.4)', marginBottom:12, animation:'pulse 2.5s infinite' }}>
          Start Placement →
        </button>
        <button onClick={async () => {
            localStorage.setItem('mt_placement_done', 'true');
            localStorage.setItem('mt_placement_level', 'a1');
            if (user) {
              await updateUserProfile(user.uid, {
                placementDone: true, placementLevel: 'a1', placementTrack: 'travel',
              }).catch(() => {});
            }
            router.push('/lingua');
          }}
          style={{ background:'none', border:'none', color:'#475569', fontSize:13, fontWeight:700, cursor:'pointer', fontFamily:"'Nunito',sans-serif" }}>
          Skip — start from A1
        </button>
      </div>
    </div>
  );

  // ════════════════════════════════════════════════════════════════════════════
  // TRACK QUIZ
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'track') {
    const tq = TRACK_QUESTIONS[trackStep];
    return (
      <div style={{ minHeight:'100vh', background:'#0F172A', display:'flex', flexDirection:'column', alignItems:'center', fontFamily:"'Nunito',sans-serif", padding:'28px 20px' }}>
        <style suppressHydrationWarning dangerouslySetInnerHTML={{ __html:`
          @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');
          @keyframes fadeUp{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}
          .topt{transition:all .15s!important;border:1.5px solid #334155!important;background:#1E293B!important;color:#CBD5E1!important;}
          .topt:hover{border-color:#F59E0B!important;background:#F59E0B15!important;transform:translateX(4px)!important;}
        `}} />

        <div style={{ width:'100%', maxWidth:520, marginBottom:28 }}>
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:10 }}>
            <div style={{ display:'flex', alignItems:'center', gap:8 }}>
              <span style={{ fontSize:16 }}>🧭</span>
              <span style={{ fontSize:12, fontWeight:900, color:'#F59E0B', letterSpacing:1.5, textTransform:'uppercase' }}>Track Discovery</span>
            </div>
            <span style={{ fontSize:12, fontWeight:800, color:'#475569' }}>{trackStep+1} / {TRACK_QUESTIONS.length}</span>
          </div>
          <ProgressBar pct={(trackStep+1)/TRACK_QUESTIONS.length*100} color="#F59E0B" />
        </div>

        <div style={{ maxWidth:520, width:'100%', animation:'fadeUp .3s ease' }} key={`tq-${trackStep}`}>
          <div style={{ background:'#1E293B', borderRadius:18, padding:'26px', border:'1px solid #334155', marginBottom:14, textAlign:'center' }}>
            <div style={{ fontSize:11, fontWeight:900, color:'#F59E0B', letterSpacing:1.5, textTransform:'uppercase', marginBottom:10 }}>
              Question {trackStep+1}
            </div>
            <div style={{ fontSize:18, fontWeight:900, color:'#F1F5F9', lineHeight:1.6 }}>{tq.q}</div>
          </div>
          <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
            {tq.options.map((opt, i) => (
              <button key={i} className="topt"
                onClick={() => handleTrackAnswer(i)}
                style={{ borderRadius:12, padding:'15px 18px', fontSize:15, fontWeight:800, textAlign:'left', cursor:'pointer', fontFamily:"'Nunito',sans-serif", display:'flex', alignItems:'center', gap:12 }}>
                <span style={{ width:26, height:26, borderRadius:'50%', background:'#334155', display:'flex', alignItems:'center', justifyContent:'center', fontSize:11, fontWeight:900, color:'#64748B', flexShrink:0 }}>
                  {String.fromCharCode(65+i)}
                </span>
                {opt}
              </button>
            ))}
          </div>
        </div>
      </div>
    );
  }

  // ════════════════════════════════════════════════════════════════════════════
  // LOADING
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'loading') return (
    <div style={{ minHeight:'100vh', background:'#0F172A', display:'flex', alignItems:'center', justifyContent:'center', fontFamily:"'Nunito',sans-serif" }}>
      <style suppressHydrationWarning dangerouslySetInnerHTML={{ __html:`
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');
        @keyframes spin{to{transform:rotate(360deg)}}
        @keyframes pulse2{0%,100%{opacity:1}50%{opacity:.4}}
      `}} />
      <div style={{ textAlign:'center' }}>
        {trackResult && (
          <div style={{ marginBottom:20 }}>
            <span style={{ display:'inline-flex', alignItems:'center', gap:8, background:TRACK_META[trackResult.track].color+'22', border:`1px solid ${TRACK_META[trackResult.track].color}44`, borderRadius:99, padding:'6px 16px', fontSize:13, fontWeight:900, color:TRACK_META[trackResult.track].color }}>
              {TRACK_META[trackResult.track].emoji} {TRACK_META[trackResult.track].label} track found
            </span>
          </div>
        )}
        <div style={{ fontSize:36, marginBottom:14 }}>{langInfo?.flag || '🌐'}</div>
        <div style={{ width:40, height:40, border:'4px solid #334155', borderTopColor:'#6366F1', borderRadius:'50%', animation:'spin .8s linear infinite', margin:'0 auto 16px' }} />
        <div style={{ fontSize:15, fontWeight:800, color:'#fff', marginBottom:6 }}>
          Generating your {langLabel} level test…
        </div>
        <div style={{ fontSize:13, color:'#475569', fontWeight:700, animation:'pulse2 1.5s infinite' }}>
          AI is crafting 10 personalised questions
        </div>
      </div>
    </div>
  );

  // ════════════════════════════════════════════════════════════════════════════
  // CEFR QUIZ
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'cefr' && cefrQ && cefrQLevel) return (
    <div style={{ minHeight:'100vh', background:'#0F172A', display:'flex', flexDirection:'column', alignItems:'center', fontFamily:"'Nunito',sans-serif", padding:'28px 20px' }}>
      <style suppressHydrationWarning dangerouslySetInnerHTML={{ __html:`
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');
        @keyframes fadeUp{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}
        .copt{transition:all .15s!important}.copt:hover:not(:disabled){transform:translateX(4px)!important}
      `}} />

      {/* Track reminder badge */}
      {trackResult && (
        <div style={{ marginBottom:16, alignSelf:'flex-start', maxWidth:520, width:'100%' }}>
          <span style={{ display:'inline-flex', alignItems:'center', gap:6, background:TRACK_META[trackResult.track].color+'18', border:`1px solid ${TRACK_META[trackResult.track].color}33`, borderRadius:99, padding:'3px 12px', fontSize:11, fontWeight:900, color:TRACK_META[trackResult.track].color }}>
            {TRACK_META[trackResult.track].emoji} {TRACK_META[trackResult.track].label}
          </span>
        </div>
      )}

      <div style={{ width:'100%', maxWidth:520, marginBottom:22 }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:10 }}>
          <div style={{ display:'flex', alignItems:'center', gap:8 }}>
            <span style={{ fontSize:16 }}>{langInfo?.flag || '🌐'}</span>
            <span style={{ fontSize:12, fontWeight:900, color:'#6366F1', letterSpacing:1.5, textTransform:'uppercase' }}>{langLabel} Level Test</span>
          </div>
          <span style={{ fontSize:12, fontWeight:800, color:'#475569' }}>{cefrStep+1} / {questions.length}</span>
        </div>
        <ProgressBar pct={(cefrStep+1)/questions.length*100} />
      </div>

      <div style={{ marginBottom:14 }} key={`cb-${cefrStep}`}>
        <span style={{ display:'inline-flex', alignItems:'center', gap:6, padding:'4px 12px', borderRadius:99, background:cefrQLevel.color+'22', border:`1px solid ${cefrQLevel.color}44`, fontSize:11, fontWeight:900, color:cefrQLevel.color, letterSpacing:1 }}>
          {cefrQLevel.emoji} {cefrQ.level.toUpperCase()} LEVEL
        </span>
      </div>

      <div style={{ maxWidth:520, width:'100%', animation:'fadeUp .3s ease' }} key={`cq-${cefrStep}`}>
        <div style={{ background:'#1E293B', borderRadius:18, padding:'24px', border:'1px solid #334155', marginBottom:12, textAlign:'center' }}>
          <div style={{ fontSize:18, fontWeight:900, color:'#F1F5F9', lineHeight:1.6 }}>{cefrQ.q}</div>
        </div>
        <div style={{ display:'flex', flexDirection:'column', gap:10, marginBottom:16 }}>
          {cefrQ.options.map((opt,i) => {
            const isSel = cefrSelected===i, isCorr = i===cefrQ.answer;
            let bg='#1E293B', border='1px solid #334155', color='#CBD5E1';
            if (cefrRevealed) {
              if (isCorr)      { bg='#064E3B'; border='1px solid #059669'; color='#6EE7B7'; }
              else if (isSel)  { bg='#450A0A'; border='1px solid #DC2626'; color='#FCA5A5'; }
            } else if (isSel)  { bg='#1E3A8A'; border='1px solid #6366F1'; color='#fff'; }
            return (
              <button key={i} className="copt" onClick={() => handleCefrAnswer(i)} disabled={cefrRevealed}
                style={{ background:bg, border, borderRadius:12, padding:'14px 18px', color, fontSize:15, fontWeight:800, textAlign:'left', cursor:cefrRevealed?'default':'pointer', fontFamily:"'Nunito',sans-serif", display:'flex', alignItems:'center', gap:12 }}>
                <span style={{ width:26, height:26, borderRadius:'50%', background:cefrRevealed&&isCorr?'#059669':cefrRevealed&&isSel?'#DC2626':'#334155', display:'flex', alignItems:'center', justifyContent:'center', fontSize:11, fontWeight:900, flexShrink:0, color:cefrRevealed&&(isCorr||isSel)?'#fff':'#64748B' }}>
                  {cefrRevealed&&isCorr?'✓':cefrRevealed&&isSel&&!isCorr?'✗':String.fromCharCode(65+i)}
                </span>
                {opt}
              </button>
            );
          })}
        </div>
        {!cefrRevealed && (
          <div style={{ textAlign:'center' }}>
            <button onClick={handleCefrSkip} style={{ background:'none', border:'none', color:'#475569', fontSize:12, fontWeight:700, cursor:'pointer', fontFamily:"'Nunito',sans-serif" }}>
              Skip →
            </button>
          </div>
        )}
      </div>
    </div>
  );

  // ════════════════════════════════════════════════════════════════════════════
  // RESULT
  // ════════════════════════════════════════════════════════════════════════════
  if (!levelInfo || !trackInfo || !trackResult) return null;
  return (
    <div style={{ minHeight:'100vh', background:'#0F172A', display:'flex', alignItems:'center', justifyContent:'center', fontFamily:"'Nunito',sans-serif", padding:20 }}>
      <style suppressHydrationWarning dangerouslySetInnerHTML={{ __html:`
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');
        @keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}
        @keyframes popIn{from{opacity:0;transform:scale(0.6)}to{opacity:1;transform:scale(1)}}
      `}} />

      <div style={{ maxWidth:480, width:'100%', animation:'fadeUp .5s ease' }}>

        {/* Celebration */}
        <div style={{ textAlign:'center', marginBottom:28 }}>
          <div style={{ fontSize:48, marginBottom:8 }}>🎉</div>
          <div style={{ fontSize:13, fontWeight:900, color:'#94A3B8', letterSpacing:2, textTransform:'uppercase' }}>
            Placement Complete
          </div>
        </div>

        {/* Track result card */}
        <div style={{ background:trackInfo.color+'0D', border:`2px solid ${trackInfo.color}44`, borderRadius:18, padding:'20px', marginBottom:14 }}>
          <div style={{ display:'flex', alignItems:'center', gap:14, marginBottom:10 }}>
            <div style={{ fontSize:36 }}>{trackInfo.emoji}</div>
            <div>
              <div style={{ fontSize:11, fontWeight:900, color:trackInfo.color, letterSpacing:1, textTransform:'uppercase' }}>Recommended Track</div>
              <div style={{ fontSize:20, fontWeight:900, color:'#fff', marginTop:2 }}>{trackInfo.label}</div>
            </div>
          </div>
          <div style={{ fontSize:13, color:'#94A3B8', fontWeight:700 }}>{trackInfo.desc}</div>
        </div>

        {/* CEFR level card */}
        <div style={{ background:levelInfo.color+'0D', border:`2px solid ${levelInfo.color}44`, borderRadius:18, padding:'20px', marginBottom:14, display:'flex', alignItems:'center', gap:16 }}>
          <div style={{ width:64, height:64, borderRadius:'50%', background:`linear-gradient(135deg,${levelInfo.color},${levelInfo.color}88)`, display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', flexShrink:0, animation:'popIn .5s cubic-bezier(.34,1.56,.64,1) .2s both' }}>
            <div style={{ fontSize:22 }}>{levelInfo.emoji}</div>
            <div style={{ fontSize:10, fontWeight:900, color:'#fff' }}>{cefrLevel.toUpperCase()}</div>
          </div>
          <div>
            <div style={{ fontSize:11, fontWeight:900, color:levelInfo.color, letterSpacing:1, textTransform:'uppercase' }}>
              {langInfo?.flag} {langLabel} Level
            </div>
            <div style={{ fontSize:18, fontWeight:900, color:'#fff', marginTop:2 }}>{levelInfo.label}</div>
            <div style={{ fontSize:12, color:'#94A3B8', fontWeight:700, marginTop:2 }}>{levelInfo.desc}</div>
          </div>
        </div>

        {/* Track fit scores */}
        <div style={{ background:'#1E293B', borderRadius:16, padding:'18px 20px', marginBottom:14, border:'1px solid #334155' }}>
          <div style={{ fontSize:11, fontWeight:900, color:'#64748B', letterSpacing:1.5, textTransform:'uppercase', marginBottom:14 }}>Track Fit Analysis</div>
          {(Object.entries(trackResult.scores) as [TrackKey, number][]).map(([t, s]) => {
            const tm = TRACK_META[t];
            const pct = Math.round(s / totalTrackScore * 100);
            return (
              <div key={t} style={{ marginBottom:12 }}>
                <div style={{ display:'flex', justifyContent:'space-between', marginBottom:5 }}>
                  <span style={{ fontSize:12, fontWeight:800, color:'#94A3B8' }}>{tm.emoji} {tm.label}</span>
                  <span style={{ fontSize:12, fontWeight:900, color:tm.color }}>{pct}%</span>
                </div>
                <ProgressBar pct={pct} color={tm.color} />
              </div>
            );
          })}
        </div>

        {/* CEFR quiz score */}
        <div style={{ background:'#1E293B', borderRadius:14, padding:'14px 18px', marginBottom:20, border:'1px solid #334155', display:'flex', justifyContent:'space-around' }}>
          {[
            { val:cefrCorrect, label:'Correct', color:'#6366F1' },
            { val:questions.length-cefrCorrect, label:'Wrong',   color:'#475569' },
            { val:`${Math.round(cefrCorrect/Math.max(questions.length,1)*100)}%`, label:'Accuracy', color:levelInfo.color },
          ].map((s,i) => (
            <div key={i} style={{ textAlign:'center' }}>
              <div style={{ fontSize:22, fontWeight:900, color:s.color }}>{s.val}</div>
              <div style={{ fontSize:10, color:'#64748B', fontWeight:700, marginTop:2 }}>{s.label}</div>
            </div>
          ))}
        </div>

        {/* XP note */}
        <div style={{ background:'#1E293B', borderRadius:12, padding:'11px 16px', marginBottom:16, border:'1px solid #334155', fontSize:13, color:'#94A3B8', fontWeight:700, textAlign:'center' }}>
          Starting XP → <strong style={{ color:levelInfo.color }}>{LEVEL_XP[cefrLevel].toLocaleString()} XP</strong> &nbsp;·&nbsp; unlocks all content up to <strong style={{ color:'#fff' }}>{cefrLevel.toUpperCase()}</strong>
        </div>

        <button onClick={handleApply} disabled={saving}
          style={{ width:'100%', padding:'14px', borderRadius:14, border:'none', background:saving?'#334155':`linear-gradient(135deg,${levelInfo.color},${levelInfo.color}bb)`, color:'#fff', fontSize:16, fontWeight:900, cursor:saving?'default':'pointer', fontFamily:"'Nunito',sans-serif", boxShadow:saving?'none':`0 8px 22px ${levelInfo.color}44`, marginBottom:10 }}>
          {saving ? 'Saving...' : `Start ${trackInfo.emoji} ${trackInfo.label} at ${cefrLevel.toUpperCase()} →`}
        </button>
        <div style={{ textAlign:'center' }}>
          <button onClick={resetAll} style={{ background:'none', border:'none', color:'#475569', fontSize:13, fontWeight:700, cursor:'pointer', fontFamily:"'Nunito',sans-serif" }}>
            Retake the test
          </button>
        </div>
      </div>
    </div>
  );
}

import { Suspense } from 'react';

export default function PlacementPage() {
  return (
    <Suspense fallback={
      <div style={{ minHeight: '100vh', background: '#0F172A', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ width: 40, height: 40, border: '4px solid #334155', borderTopColor: '#6366F1', borderRadius: '50%', animation: 'spin .8s linear infinite' }} />
        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
      </div>
    }>
      <PlacementInner />
    </Suspense>
  );
}
